---
title: "Seven shiny apps"
author:
  - name: Danielle Navarro
    url: https://djnavarro.net
    affiliation: I'm on smoko
    affiliation-url: https://www.youtube.com/watch?v=j58V2vC9EPc
    orcid: 0000-0001-7648-6578
description: "One app per day for a week"
date: "2023-03-24"
categories: [Shiny, R]
---

<!--------------- my typical setup ----------------->

```{r setup, include=FALSE}
wide <- 136
narrow <- 76
options(width = narrow)
cache_images <- TRUE
```

<!--------------- post begins here ----------------->

## App 1: Shattered lands


- The app: [djnavarro.shinyapps.io/shattered-landscapes](https://djnavarro.shinyapps.io/shattered-landscapes/)
- The source: [app.R](app-1/app.R)

Things I like:

- It works! It turns out that I haven't forgotten how to write Shiny apps
- It uses `bslib::bs_theme()` to lightly customise the theme
- It uses `colourpicker::colourInput()` to allow the user to input colours
- It uses `shinycssloaders::withSpinner()` to ask the user to wait for rendering
- It only generates an image when the action button is pressed


Things I wish it did better:

- I had to simplify it so that I wouldn't get out-of-memory errors on shinyapps.io
- The CSS code to scale the image size in `plotOutput()` isn't ideal
- It should probably use `bindCache()` to avoid recalculating outputs that have previously been computed for a given seed value



<!--------------- appendices go here ----------------->


