---
title: "Another year ends"
description: "Some say the year ends in fire, some say in ice. As to my own desire, any end at all will be nice."
date: "2023-12-16"
--- 

<!--------------- my typical setup ----------------->

```{r}
#| label: setup
#| include: false
very_wide <- 500
wide <- 136
narrow <- 76
options(width = narrow)
cache_images <- TRUE
set.seed(1)
```

<!--------------- post begins here ----------------->

:::{.callout-warning}
Content note: This post refers briefly to sexual assault
:::

At the end of last year I wrote a wrap-up post listing the things I'd done during 2022, ([A Very Strange Year](/posts/2022-12-26_strange-year/)), and perhaps I'll do another one for 2023.



## Data science, tech, and statistics

Not surprisingly given the focus on data science on this blog, I wrote a number posts about R packages and related topics in tech during 2023. Several of them were posts where I chose an R package that I wanted to play around with and wrote about it:

- [The santoku package](/posts/2023-05-22_santoku/)
- [The pins package](/posts/2023-06-12_pins-and-needles/)
- [The asciicast package](/posts/2023-06-14_ansi-tricks/)
- [The tabulizer package](/posts/2023-06-16_tabulizer/)

Others were built around a specific topic, though still very heavily focused on workflows in R:

- [Running R on the web with webR](/posts/2023-04-09_webr/)
- [Assertion checking in R](/posts/2023-08-08_being-assertive/)

Not all of my tech posts were about R though. Some are general purpose posts in which I taught myself new tools: learning about Docker and Kubernetes was fun, though in truth I've not had much opportunity to use either of these skills.^[I mean, let's face it: while there's a strong case to be made that Docker is an important tool for a lot of scientists, Kubernetes is ... not. I learned it because it's occasionally relevant for deploying applications at scale, but that's not at all relevant in my current role.] On the other hand, learning about Makefiles was super useful and I've found myself using them a lot.^[Yes yes, I know, there are many alternatives, and if I'm an R person I should probably get off my lazy arse and learn [targets](https://books.ropensci.org/targets/) but life is short and I am tired okay?] 

- [Playing with docker and the github container registry](/posts/2023-01-01_playing-with-docker/)
- [Deploying R with kubernetes](/posts/2023-01-10_kubernetes/)
- [Makefiles. Or, the balrog and the submersible](/posts/2023-06-30_makefiles/)

In a refreshing change for this blog -- which has historically focused on code -- I started writing a little more about statistical inference this year. Not as much as I'd have liked, and not as in-depth as I'd have liked either, but perhaps it will be the beginning of a trend for me. Two old statistics posts returned from the dead in 2023, both relics from my former life as an academic,^[Strangely, despite being out of academia for over two years now, [papers](https://papers.djnavarro.net) from that life still continue to trickle out, and another six journal articles emerged in 2023 that have my name on them. Academia really makes it hard for you to draw a line in the sand, which... actually is not great when the reason you left is not a pleasant one. Sigh.] and a third post estimating the number of internally displaced trans people within the United States:

- [A gentle introduction to the Metropolis-Hastings algorithm](/posts/2023-04-12_metropolis-hastings/)
- [A personal essay on Bayes factors](/posts/2023-04-12_bayes-factors/)
- [On living in dark times](/posts/2023-06-15_dark-times/)

Finally, I wrote a couple of other posts on other topics broadly related to data science and software. My new personal machine is (for reasons!) using Windows as the primary OS, with an Ubuntu installation ([no, not Arch](/posts/2022-12-31_btw-i-use-arch/)) running concurrently thanks to Windows Subsystem for Linux. I wrote about some of the practicalities of using a setup like this, and specifically about how to use the RStudio IDE and VS Code effectively if you're using linux for your data science work but you want your IDE to run smoothly as a windows application:

- [RStudio and VS Code in WSL](/posts/2023-07-02_the-ides-of-wsl/)

Oh, and I wrote a book review of Greg Wilson's "Software design by example" in which I followed his guidance and wrote a regular expression tokeniser:

- [Software design by example](/posts/2023-05-31_software-design-by-example/)

That one was fun, and I learned a lot.

## Pharmacometrics

Around the middle of the year I managed to find work, which came as something of a relief. My new role is in [pharmacometrics](https://en.wikipedia.org/wiki/Pharmacometrics), and while the job is pretty intense -- honestly, I'm working longer hours now than I did even as an academic -- it's been rewarding. There's a lot of new and fascinating things to learn, and I do love being able to learn new things. That's shown up in this blog quite a bit this year, with several posts discussing pharmacokinetic (PK) models generally and population-pharmacokinetic (pop-PK) models specifically:

- [Non-compartmental analysis](/posts/2023-04-26_non-compartmental-analysis/)
- [Simple PK models in Stan](/posts/2023-05-16_stan-ode/)
- [Minimal pop-PK models in Stan](/posts/2023-06-10_pop-pk-models/)
- [Getting started with pop-PK in Torsten](/posts/2023-07-15_torsten/)
- [Simulating from PK models with mrgsolve](/posts/2023-08-14_mrgsolve/)
- [Simulating from PK models with rxode2](/posts/2023-08-28_rxode2/)

There's several other topics in this area I want to write, especially now that my knowledge of the field is considerably stronger than it was when I wrote these pieces.^[Gonna be honest: I now look at most of these pieces and smile. They're good posts, really, but I can now spot a *lot* of things in each of them that reveal that the author didn't have a lot of practical experience with PK modelling at the time. But that's good -- that's what happens when you learn things!] It's likely I'll write more posts about pharmacometrics in 2024, but probably at a slower rate. That's mostly because the nature of my employment is different these days: all my previous jobs before this one were in some sense public-facing roles, and writing blog posts about the substantive topic were part and parcel of the job itself. That's not the case in my current role, so any writing I do is "off the books" so to speak, and only happens when I have spare time. Which is entirely okay, of course, but it's hardly a surprise that it's easier to find time to do a thing when it is central to your job than it is to do the same thing when it's not actually part of the role!^[This lack of time, incidentally, is also the reason why I haven't done much work on the ggplot2 book this year, and haven't done much of the work on updating "learning statistics with R" this year either. It's a little sad because I care a lot about both of those projects but neither one pays the rent, and that's a hell of a factor when you live in Sydney.]

## Art

On the art front, I changed course a bit in 2023. Early in the year I reluctantly concluded that there isn't any point in trying to generate income from my art. I haven't been taking commissions, I turned down a few opportunities to write books on generative art, and I haven't been doing workshops the way I used to. There are a couple of reasons for that, but mostly they boil down to "return on investment". It takes a lot of time, energy, and *work* to do the things that allow you to make money from art, and the bitter truth to it is that unless you're one of the lucky few who "makes it big", you really don't make enough money from the art to justify the effort.^[And, yes, with the rise of tools like DALL-E and midjourney, the situation has gotten worse over the past year.] People love art. They don't love paying for it. Nowadays I don't even bother to try: I make art when I feel like making art, I write about art when I feel like writing about art, and that's it. 

That doesn't mean I abandoned making art of course, or even writing about it. I wrote three blog posts on generative art this year, for example:

- [Generative art with p5.js](/posts/2023-01-14_p5js/)
- [Making shattered landscapes in R](/posts/2023-03-13_shattered-landscapes/)
- [Generative art with grid](/posts/2023-03-31_generative-art-with-grid/)

I published seven art series on my art website, mostly created with R but also with javascript in some cases:

- [Subdivision](https://art.djnavarro.net/gallery/subdivision/)
- [Broken lands](https://art.djnavarro.net/gallery/broken-lands/)
- [Bound](https://art.djnavarro.net/gallery/bound/)
- [Curled](https://art.djnavarro.net/gallery/curled/)
- [Splotches](https://art.djnavarro.net/gallery/splotches/)
- [Pastiche](https://art.djnavarro.net/gallery/pastiche/)
- [Advent](https://art.djnavarro.net/gallery/advent/)

I even wrote a custom [arttools](https://arttools.djnavarro.net/) R package that I use to help me manage my art workflows,^[Note that it's not a tool for making generative art, it's a tool for managing art repos and organising output in a format that makes it easy for me to publish art to my website. It's also not intended for general use. I wrote the package for myself. For anyone else it's a "use at your own risk" kind of deal. You can use it if it's useful for you, but I have no intention whatsoever of maintaining it for any purpose except my own use.] and gave an invited talk at the University of Auckland on generative art ([unpredictable paintings](https://djnavarro.net/slides-auckland-2023/)). I'm grateful to the lovely folks at Auckland for the invitation, and it was really wonderful to give the talk to such a kind audience. 

So yeah. I'm still making art and sharing it on mastodon, but mostly as a hobbyist these days. I've lost any real desire to be a professional artist, and that's okay. Sometimes a hobby can be just a hobby. Not everything in life needs to be a side hustle. 

