---
output: 
  pdf_document:
    latex_engine: pdflatex
    template: ./svm-latex-cv.tex
geometry: margin=.75in

author: "Danielle Navarro"
title: "Academic Résumé"

jobtitle: "Associate Professor, School of Psychology, University of New South Wales, Sydney"
fontawesome: yes
email: d.navarro@unsw.edu.au
github: djnavarro
twitter: djnavarro
phone: "0421 488 402"
web: djnavarro.net
updated: no

fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 10pt
linkcolor: blue
urlcolor: blue
---

# Biography, Education & Employment

My Ph.D. was awarded in 2003 by the University of Adelaide, where I was appointed Lecturer in 2006, promoted to Senior Lecturer in 2009 & Associate Professor in 2013. I held multiple Australian Research Council (ARC) Fellowships from 2007-2015 & from 2016 have been Associate Professor at UNSW Sydney. 


# Research Overview

My research interests lie within the field of computational cognitive science - I study the mathematical and computational basis for human intelligence, with a view to connecting this to animal and machine intelligence. With this in mind, my work covers a wide range of topics in psychology. I have made major contributions to understanding basic information processing (associative learning, similarity, reaction time), higher order cognition (categorisation, reasoning, decision making) and the social nature of human intelligence (iterated learning, language evolution, cultural evolution). My interests include topics in research methodology (statistics education, robust inference, model selection) where I have made substantial contributions.

I have published extensively in the top journals in psychology, including 5 papers in *Psychological Review* -- the top theoretical journal in the field -- with numerous papers published in the top journals in cognitive and experimental psychology (e.g., *Journal of Experimental Psychology: General*, *Cognitive Psychology*, *Cognitive Science*; see [djnavarro.net/papers](https://djnavarro.net/papers/)), all Q1 Ranked according to Science Journal Reports (SJR). 

Bibliometric summary: I have published over 150 peer reviewed journal articles, scholarly book chapters and conference proceedings papers. According to Google Scholar ([scholar.djnavarro.net](http://scholar.djnavarro.net)), my h-index is 35 and my work has been cited 470 times, with 751 citations in 2020. Recent papers I like include:

  - Navarro (2019). Between the devil and the deep blue sea: Tensions between scientific judgement and statistical model selection. *Computational Brain & Behavior, 2*, 28-34 ([psyarxiv.com/39q8y](https://psyarxiv.com/39q8y/))
  - De Deyne, Navarro, Perfors, Brysbaert & Storms (2019). The Small World of Words: English word association norms for over 12,000 cue words. *Behavior Research Methods, 51*, 987-1006 ([psyarxiv.com/mb93p](https://psyarxiv.com/mb93p/))
  - Tauber, Navarro, Perfors & Steyvers (2017). Bayesian models of cognition revisited: Setting optimality aside and letting data drive psychological theory. *Psychological Review, 124*, 410-441 ([psyarxiv.com/25gcm](https://psyarxiv.com/25gcm/))


# Teaching & Training

My university teaching has focused on teaching statistics and cognitive science at an undergraduate and postgraduate level; across my teaching career the median "broad approval rating" in my student evaluations is 97%. My teaching materials are available at [djnavarro.net/teaching](https://djnavarro.net/teaching), including the following university courses:

- *Robust Tools*, a 4th year data science class in 9 two-hour workshops
- *Minds & Machines*, a 4th year R programming & cognitive science class in 9 two-hour workshops
- *R for Psychological Science*, a 3rd year R programming class in 6 two-hour workshops
- *Perception & Cognition*, an 2nd year introduction to cognitive psychology in 6 one-hour lectures
- *Cognitive Science*, a 3rd year introduction to cognitive modelling in 6 one-hour lectures
- *Computational Cognitive Science*, a 3rd year computer science class in 27 one-hour lectures

Also listed are the following resources:

- *Learning Statistics with R*, a free open access textbook that has been adapted for the JASP and jamovi software packages, with a translation to French (plus proposed translations to Japanese & Spanish)
- *Data Visualisation*, materials for a half-day workshop teaching ggplot2 and gganimate
- *Complex Human Data Summer School*, a 6-day summer school on modern research tools

I currently supervise 2 postdoctoral researchers and 1 Ph.D. student. I previously have supervised 6 postdoctoral researchers, 11 PhD students and 21 honours/masters students. Most of my PhD students tend to go on take postdoctoral research positions (7/11), with 3 taking jobs in industry and1 undertaking further study. Postdoctoral researchers in my lab have taken academic posts (3/6), research fellowships (3/6) or jobs in industry (1/6).


# Research Funding 

I have won 8 Australian Research Council grants (total value $3m) with continuous funding from 2004:

- Hayes, Navarro & Kemp 2019-2021. Bayesian reasoning from censored data. DP190101224. $390k
- Navarro & Newell 2019-2021. The psychology of not wanting to know. DP190101076. $430k
- Navarro & Lee 2015-2018. Learning and choosing in a complex world. DP150104206. $330k
- Navarro 2012-2016. Learning structured mental representations from data. FT110100431. $608k
- Navarro, Perfors & Tenenbaum 2011-2014. Bayesian models of inductive inference. DP110104949. $445k
- Navarro 2007-2011. Bayesian models for human conceptual learning. DP0773794. $510k
- Navarro, Lee & Maio Mackay 2005-2007. User profiling in telecommunications. LP0562206. $449k
- Lee & Navarro 2004-2006. Cognitive models that account for individual differences. DP0451793. $230k

Research grants, contracts and consultancies valued at \$10k or more are listed below:

- Falster & 11 others inc. Navarro 2020. Building quality software in R. UNSW Research Infrastructure: $235k
- Martire, Towler & Navarro 2018. Limits & acquisition of expertise in forensic sciences. UNSW Faculty: $20k
- Martire, Newell & Navarro 2018. Human probability judgments. UNSW Gold Star: $40k
- Ma-Wyatt, Burns, Dunn & Navarro 2014. Equipment grant. UoA Faculty: $27k
- Navarro 2007. Decision-making in an oil & gas context. Exxon & Santos (via UoA School of Petroleum) $35k 
- Navarro 2007. Social network analysis. Defense R&D Canada: $22k
- Navarro 2005. Similarity judgments on email. DST Group: $33k

# Awards, Fellowships & Prizes

I have received various awards and fellowships, including:

- Computational Brain and Behaviour Outstanding Paper Award 2021
- Executive Dean's Teaching and Learning Prize 2013, University of Adelaide.
- ARC Future Fellowship 2012-2015, Australian Research Council
- ARC Australian Research Fellowship 2007-2011, Australian Research Council
- William K Estes Early Career Award 2007, Society for Mathematical Psychology

Researchers in my group have also won awards for papers/presentations that I coauthored:

- Simon De Deyne: Best paper award, Behavior Research Methods, 2019
- Belinda Xie: Best student presentation, Experimental Psychology Conference 2018
- Simon De Deyne: Best paper award, Computational Linguistics 2016
- Wai Keen Vong: Marr prize for best student paper, Cognitive Science conference 2016
- Steven Langsford: Best student presentation, Experimental Psychology Conference 2015

# Outreach & Service

I have served on the Board of Reviewing Editors at *Science* (2020-2021) and as a Consulting Editor at *Psychological Review* (2021). I previously held Associate Editor positions at three prestigious journals: *Open Mind: Discoveries in Cognitive Science* (2016-2019), *Behavior Research Methods* (2014-2016), and *Cognitive Science* (2011-2013).

I have organised several small workshops and three national level conferences: 

- *Australasian Mathematical Psychology Conference*. February 2020.
- *Australasian Experimental Psychology Conference*. April 2013.
- *Australasian Mathematical Psychology Conference*. February 2012.

In my previous position I held substantial administrative roles (e.g., chair of school research committee). My administrative profile at UNSW is modest has included roles organising school colloquia, serving on the school equity committee and advocating for LGBTQI inclusion within the university.

In 2018 I co-founded R-Ladies Sydney, a group that promotes gender diversity within the R programming community, which now has over 700 members. I have been active in the Australian rOpenSci organisation that develops free and open source software for Australian science applications. 
